---
version: 2.5.2.2
slug: mariadb
name: In-memory MariaDB
description: An in-memory SQL database server
url: https://github.com/lmagyar/homeassistant-addon-mariadb-inmemory
codenotary: lmagyar1973@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
tmpfs: true
privileged:
  - SYS_ADMIN
map:
  - share:rw
backup_pre: call-export-homeassistant-database
image: ghcr.io/lmagyar/{arch}-addon-mariadb-inmemory-beta
init: false
options:
  tmpfs:
    size: 200m
  retention:
    enabled: true
    periodic: disabled
  purge_statistics:
    period: monthly
    keep_periods: 6
    archive: false
  databases:
    - homeassistant
  logins:
    - password: null
      username: homeassistant
  rights:
    - database: homeassistant
      username: homeassistant
ports:
  3306/tcp:
schema:
  tmpfs:
    size: match(^\d+[kmg]?$)
  retention:
    enabled: bool
    periodic: list(disabled|hourly|daily|weekly|monthly)
  purge_statistics:
    period: list(daily|weekly|monthly)
    keep_periods: int(1,)
    archive: bool
  databases:
    - str
  logins:
    - username: str
      password: password
  rights:
    - database: str
      privileges:
        - "list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|\
           CREATE VIEW|DELETE|DELETE HISTORY|DROP|EVENT|GRANT OPTION|INDEX|\
           INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?"
      username: str
services:
  - mysql:provide
startup: system
timeout: 300
