---
version: 2.5.0.0
homeassistant: 2022.6.0
slug: mariadb
name: In-memory MariaDB
description: An in-memory SQL database server
url: https://github.com/lmagyar/homeassistant-addon-mariadb-inmemory
codenotary: lmagyar1973@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
tmpfs: true
privileged:
  - SYS_ADMIN
backup_post: /command/s6-svc -wd -d /run/service/mariadb-lock/
backup_pre: /command/s6-svc -wU -u /run/service/mariadb-lock/
image: lmagyar/{arch}-addon-mariadb-inmemory
init: false
options:
  tmpfs:
    size: 200m
  databases:
    - homeassistant
  logins:
    - password: null
      username: homeassistant
  rights:
    - database: homeassistant
      username: homeassistant
ports:
  3306/tcp:
schema:
  tmpfs:
    size: match(^\d+[kmg]?$)
  databases:
    - str
  logins:
    - username: str
      password: password
  rights:
    - database: str
      privileges:
        - "list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|\
           CREATE VIEW|DELETE|DELETE HISTORY|DROP|EVENT|GRANT OPTION|INDEX|\
           INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?"
      username: str
services:
  - mysql:provide
startup: system
timeout: 20

